# Generated by Django 5.2.14 on 2026-06-18 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramStarPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('telegram_username', models.CharField(blank=True, max_length=80)),
                ('telegram_first_name', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='XTR', max_length=8)),
                ('stars_amount', models.PositiveIntegerField()),
                ('cherryx_amount', models.PositiveIntegerField(default=0)),
                ('plan_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending_link', 'Pending account link'), ('credited', 'Credited')], db_index=True, default='pending_link', max_length=20)),
                ('invoice_payload', models.CharField(db_index=True, max_length=160)),
                ('telegram_payment_charge_id', models.CharField(max_length=160, unique=True)),
                ('provider_payment_charge_id', models.CharField(blank=True, max_length=160)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_star_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_user_id', '-created_at'], name='billing_tel_telegra_f929cf_idx'), models.Index(fields=['user', '-created_at'], name='billing_tel_user_id_1bb61b_idx')],
            },
        ),
    ]
