# Generated by Django 5.2.14 on 2026-06-19 08:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_telegramstarpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='telegram_promotions/')),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True, max_length=600)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sent', 'Sent')], db_index=True, default='draft', max_length=16)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramPaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=48, unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('plan', 'Plan'), ('topup', 'Top up')], max_length=12)),
                ('plan_code', models.CharField(blank=True, max_length=40)),
                ('cherryx_amount', models.PositiveIntegerField(default=0)),
                ('stars_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('needs_email', 'Needs email'), ('applied', 'Applied'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('invoice_payload', models.CharField(blank=True, db_index=True, max_length=160)),
                ('telegram_payment_charge_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('provider_payment_charge_id', models.CharField(blank=True, max_length=160)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_user_id', '-created_at'], name='billing_tel_telegra_0118d9_idx'), models.Index(fields=['status', 'expires_at'], name='billing_tel_status_05ba87_idx')],
            },
        ),
    ]
