# Generated by Django 5.2.14 on 2026-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_jobeventrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecord',
            name='params_json',
            field=models.TextField(blank=True),
        ),
    ]
