# Generated by Django 5.2.14 on 2026-05-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_jobrecord_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecord',
            name='guest_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
