# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0009_accountprofile_interface_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoEditorProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guest_key", models.CharField(blank=True, db_index=True, max_length=80)),
                ("title", models.CharField(default="Новый проект", max_length=180)),
                ("state_json", models.JSONField(blank=True, default=dict)),
                ("storage_bytes", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="video_editor_projects", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="videoeditorproject",
            index=models.Index(fields=["owner", "-updated_at"], name="studio_vide_owner_i_369944_idx"),
        ),
        migrations.AddIndex(
            model_name="videoeditorproject",
            index=models.Index(fields=["guest_key", "-updated_at"], name="studio_vide_guest_k_7aacff_idx"),
        ),
    ]
