# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0010_videoeditorproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoEditorAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(db_index=True, max_length=16)),
                ("file_path", models.TextField()),
                ("media_type", models.CharField(default="application/octet-stream", max_length=120)),
                ("size", models.BigIntegerField(default=0)),
                ("original_name", models.CharField(blank=True, max_length=240)),
                ("thumbnail_path", models.TextField(blank=True)),
                ("duration", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assets", to="studio.videoeditorproject")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
