# Generated by Django 5.2.14 on 2026-06-01 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_videoeditorasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, default='image', max_length=16)),
                ('file_path', models.TextField()),
                ('media_type', models.CharField(default='application/octet-stream', max_length=120)),
                ('size', models.BigIntegerField(default=0)),
                ('original_name', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DesignerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('title', models.CharField(default='New design', max_length=180)),
                ('state_json', models.JSONField(blank=True, default=dict)),
                ('storage_bytes', models.BigIntegerField(default=0)),
                ('preview_path', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='videoeditorproject',
            new_name='studio_vide_owner_i_b6850b_idx',
            old_name='studio_vide_owner_i_369944_idx',
        ),
        migrations.RenameIndex(
            model_name='videoeditorproject',
            new_name='studio_vide_guest_k_236d98_idx',
            old_name='studio_vide_guest_k_7aacff_idx',
        ),
        migrations.AddField(
            model_name='designerproject',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designerasset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.designerproject'),
        ),
        migrations.AddIndex(
            model_name='designerproject',
            index=models.Index(fields=['owner', '-updated_at'], name='studio_desi_owner_i_233787_idx'),
        ),
        migrations.AddIndex(
            model_name='designerproject',
            index=models.Index(fields=['guest_key', '-updated_at'], name='studio_desi_guest_k_bc82cd_idx'),
        ),
    ]
