# Generated by Django 5.2.14 on 2026-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_performance_denormalized_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='cherryx_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='telegram_first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='telegram_link_token',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='telegram_link_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
