# Generated by Django 5.2.14 on 2026-06-19 10:05

import django.db.models.deletion
import studio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_magiclogintoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=96, unique=True)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('text', 'Text')], db_index=True, max_length=16)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, upload_to='community/source/')),
                ('cover_image', models.ImageField(blank=True, upload_to=studio.models._webp_upload_to)),
                ('access', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid with CherryX')], db_index=True, default='free', max_length=16)),
                ('price_cherryx', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_works', to=settings.AUTH_USER_MODEL)),
                ('source_design_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_works', to='studio.designerproject')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_works', to='studio.jobrecord')),
                ('source_video_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_works', to='studio.videoeditorproject')),
            ],
            options={
                'ordering': ['-featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cherryx', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_purchases', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_sales', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='studio.communitywork')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=96, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to=studio.models._webp_upload_to)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='studio_lear_status_64bf90_idx'), models.Index(fields=['featured', 'status'], name='studio_lear_feature_c52073_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='communitywork',
            index=models.Index(fields=['kind', 'status', '-published_at'], name='studio_comm_kind_b367dd_idx'),
        ),
        migrations.AddIndex(
            model_name='communitywork',
            index=models.Index(fields=['owner', '-created_at'], name='studio_comm_owner_i_f1963b_idx'),
        ),
        migrations.AddIndex(
            model_name='communitywork',
            index=models.Index(fields=['access', 'status'], name='studio_comm_access_e60a16_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypurchase',
            index=models.Index(fields=['buyer', '-created_at'], name='studio_comm_buyer_i_26a757_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypurchase',
            index=models.Index(fields=['seller', '-created_at'], name='studio_comm_seller__fbe271_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypurchase',
            constraint=models.UniqueConstraint(fields=('work', 'buyer'), name='unique_community_purchase'),
        ),
    ]
