# Generated by Django 5.2.14 on 2026-06-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_communitywork_communitypurchase_learningarticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitywork',
            name='media_file',
            field=models.FileField(blank=True, upload_to='community/private/'),
        ),
    ]
