# Generated by Django 5.2.14 on 2026-06-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0019_alter_communitywork_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitywork',
            name='source_music_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_works', to='studio.musiceditorproject'),
        ),
        migrations.AlterField(
            model_name='communitywork',
            name='kind',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('text', 'Text'), ('music', 'Music')], db_index=True, max_length=16),
        ),
    ]
