# Generated by Django 5.2.14 on 2026-06-19 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_communitywork_source_music_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CherryXTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed')], db_index=True, default='completed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cherryx_transfers_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cherryx_transfers_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='studio_cher_sender__0bbbcd_idx'), models.Index(fields=['recipient', '-created_at'], name='studio_cher_recipie_1e81f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CherryXWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('withdrawal_hold', 'Withdrawal hold'), ('withdrawal_refund', 'Withdrawal refund'), ('withdrawal_paid', 'Withdrawal paid'), ('market_purchase', 'Market purchase'), ('market_sale', 'Market sale')], db_index=True, max_length=32)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('reversed', 'Reversed')], db_index=True, default='completed', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_cherryx_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cherryx_wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='studio_cher_user_id_483d79_idx'), models.Index(fields=['type', 'status', '-created_at'], name='studio_cher_type_6ad2da_idx')],
            },
        ),
        migrations.CreateModel(
            name='CherryXWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('amount_cherryx', models.PositiveIntegerField()),
                ('estimated_stars', models.PositiveIntegerField()),
                ('actual_paid_stars', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cherryx_withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='studio_cher_user_id_e2aae6_idx'), models.Index(fields=['status', '-created_at'], name='studio_cher_status_cdf49e_idx')],
            },
        ),
    ]
