# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0021_cherryxtransfer_cherryxwallettransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitywork",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
