from __future__ import annotations

from .localization import clean_language


DOCS_CONTENT: dict[str, dict[str, object]] = {
    "en": {
        "label": "Documentation and training",
        "title": "CherryX Creator Studio documentation",
        "description": "A practical customer guide: choose a tool, pay for access, upload files, prepare content and download ready digital results.",
        "seo": "CherryX Creator Studio documentation for digital services: video editor, music editor, design board, originality check, covers, subtitles, PDF resumes, publication packages, payments and downloads.",
        "quick": [
            ("Start", "Choose a plan or tool and open the workspace."),
            ("Upload", "Add files, text, media, links or task details."),
            ("Process", "Run the task, review previews and track progress."),
            ("Download", "Open the completed task and download ready files."),
        ],
        "sections": [
            ("1. What CherryX Creator Studio is", ["CherryX Creator Studio is a remote digital service for creating, processing and preparing creative files.", "The service works with videos, covers, subtitles, PDF resumes, design layouts, text documents, music assets and publication packages."], [("Digital only", "All results are delivered online inside the workspace."), ("Tools", "Converter, Shorts, covers, subtitles, resume, design, video, music and originality check."), ("Best for", "Creators, studios, freelancers and customers who need ready digital materials.")]),
            ("2. Basic workflow", ["Select the tool that matches the task, upload source materials and review settings before processing.", "When the task is complete, open the task card to preview and download available results."], [("Choose a tool", "Start from the goal: convert, edit, design, check text or package publication assets."), ("Prepare inputs", "Use clear file names, good source quality and accurate task details."), ("Check results", "Review preview, text, timing, format and file quality before publishing.")]),
            ("3. Payments, access and limits", ["Paid access is activated automatically after successful online payment.", "Plans can include access period, storage size, file limits, available tools and processing priority."], [("Activation", "Access normally appears in the account immediately after payment confirmation."), ("Limits", "Limits depend on the selected plan and current service rules."), ("Delivery", "No physical delivery is used; files are provided digitally.")]),
            ("4. File preparation", ["Good source materials improve the final result and reduce repeated processing.", "Before upload, check file format, size, language, aspect ratio, audio quality and platform requirements."], [("Video", "Check duration, orientation, resolution and final platform requirements."), ("Design", "Prepare title text, brand colors, references and required dimensions."), ("Documents", "Use DOCX, PDF or TXT where supported and remove private data you do not want to process.")]),
            ("5. Result review", ["Before publication, always open the preview or downloaded file and review the output manually.", "AI-assisted tools accelerate preparation, but final approval remains the customer's responsibility."], [("Text", "Check spelling, names, links, dates, prices and contacts."), ("Media", "Check sharpness, crop, audio, subtitles and export quality."), ("Repeat", "If edits are needed, rerun the task or create a new task with clearer inputs.")]),
            ("6. Support and troubleshooting", ["For support, provide the account email, payment date, plan name, task name, screenshots and a short description of the problem.", "If upload or processing fails, check file size, format, connection and try refreshing the page."], [("Payment issue", "Send payment date, amount, account email and confirmation details."), ("Upload issue", "Try a supported format, shorter file name and stable connection."), ("No result", "Check task status; complex files can take longer to process.")]),
            ("7. Video lessons and examples", ["This section contains short lessons for common CherryX Creator Studio workflows.", "Lessons help customers understand workspace navigation, payment, downloads and publication preparation."], [("Quick start", "Learn how to open the workspace, choose a tool and run the first task."), ("Payments", "Understand access activation, limits and completed downloads."), ("Publishing", "See how covers, subtitles and ZIP packages fit together.")]),
            ("8. Video editor", ["The video editor is used for preparing clips, short videos and publication-ready media.", "Use it when framing, sequence, preview, audio alignment or final export matter."], [("Import", "Upload the source video and wait for the preview to be ready."), ("Edit", "Work with scenes, order, framing and final visual logic."), ("Export", "Download the final file and review it locally before publishing.")]),
            ("9. Music editor", ["The music editor helps prepare audio assets for videos, previews and publication workflows.", "Use only audio you have the right to use, especially for public platforms."], [("Upload audio", "Add the source track and check that it opens correctly."), ("Prepare", "Review volume, duration, start, ending and important accents."), ("Rights", "Confirm music usage rights before publishing.")]),
            ("10. Design board and projects", ["The design board is a workspace for covers, previews, banners, layouts and visual assets.", "Design projects help keep separate creative tasks organized and easy to return to."], [("Projects", "Create a separate project for each cover, preview, banner or layout."), ("Elements", "Check that text and images do not hide important areas."), ("Export", "Download PNG, JPG or WEBP and review readability on mobile.")]),
            ("11. Originality, documents and text check", ["The originality section helps analyze text documents, drafts and articles for uniqueness, repetition and AI-risk indicators.", "The result is an analytical guide, not a legal, academic or editorial final judgment."], [("Text", "Paste text for a quick structure and repetition check."), ("Documents", "Upload supported DOCX, PDF or TXT files within the size limit."), ("Report", "Use the report as a checklist for rewriting, adding sources and checking facts.")]),
            ("12. Publication package", ["A publication package helps collect final assets for publishing: ZIP, preview, texts, covers, subtitles and related files.", "It is useful when materials need to be handed to a customer, editor, designer or publisher."], [("Package contents", "Check which files should be included before downloading the ZIP."), ("File names", "Use clear final names so every asset is easy to identify."), ("Final check", "Open the archive before sending or publishing.")]),
        ],
        "videos_title": "Training videos",
        "videos_copy": "Short lessons appear here when available. They explain the first launch, payment, downloads and publication workflow.",
        "videos": [
            ("Quick start", "Open the workspace, choose a tool and run the first task.", ""),
            ("Payment and downloads", "Understand access activation, limits and ready files.", ""),
            ("Publication workflow", "Prepare covers, subtitles and ZIP packages for publishing.", ""),
        ],
        "faq": [
            ("Where are my files delivered?", "All digital results are delivered in the workspace and can be downloaded from the task card."),
            ("Is there physical delivery?", "No. CherryX Creator Studio provides digital services only."),
            ("Where can I watch training videos?", "Open the training videos section. Available lessons can be watched directly in the documentation."),
            ("Can I work only with video?", "Yes. You can use the video editor or a video task without creating covers or subtitles."),
            ("Can I prepare music separately?", "Yes. The music editor can be used as a separate audio preparation tool."),
            ("What is the design board?", "It is a workspace for visual projects such as covers, previews, banners and layouts."),
            ("Is the originality check final proof?", "No. It is an analytical guide; legal, academic or editorial conclusions should be checked separately."),
            ("Can I check PDF and DOCX?", "Yes, when the selected tool supports the format and the file is within the size limit."),
            ("What should I do if AI-risk is high?", "Review the text, add sources, improve specifics and rewrite repeated template-like phrases."),
            ("How should I prepare publication materials?", "Collect final file versions, use clear names, download the ZIP package and review it before publishing."),
            ("What should I send to support?", "Send account email, payment date, task name, screenshots and a short description of the issue."),
        ],
    },
    "ru": {
        "label": "Документация и обучение",
        "title": "Документация CherryX Creator Studio",
        "description": "Практичное руководство для клиентов: выбрать инструмент, оплатить доступ, загрузить файлы, подготовить контент и скачать готовые цифровые результаты.",
        "seo": "Документация CherryX Creator Studio: видео-редактор, музыкальный редактор, дизайн-доска, проверка уникальности, обложки, субтитры, PDF-резюме, пакеты публикации, оплата и скачивание.",
        "quick": [
            ("Старт", "Выберите план или инструмент и откройте рабочее пространство."),
            ("Загрузка", "Добавьте файлы, текст, медиа, ссылки или описание задачи."),
            ("Обработка", "Запустите задачу, проверьте preview и следите за прогрессом."),
            ("Скачивание", "Откройте завершённую задачу и скачайте готовые файлы."),
        ],
        "sections": [
            ("1. Что такое CherryX Creator Studio", ["CherryX Creator Studio — дистанционный цифровой сервис для создания, обработки и подготовки креативных файлов.", "Сервис работает с видео, обложками, субтитрами, PDF-резюме, дизайн-макетами, текстовыми документами, музыкой и пакетами публикации."], [("Только цифровой формат", "Все результаты предоставляются онлайн внутри рабочего пространства."), ("Инструменты", "Конвертер, Shorts, обложки, субтитры, резюме, дизайн, видео, музыка и проверка уникальности."), ("Для кого", "Для creators, студий, фрилансеров и клиентов, которым нужны готовые цифровые материалы.")]),
            ("2. Основной сценарий работы", ["Выберите инструмент под задачу, загрузите исходные материалы и проверьте настройки перед обработкой.", "Когда задача завершится, откройте карточку задачи, проверьте preview и скачайте доступные результаты."], [("Выбор инструмента", "Начинайте с цели: конвертировать, смонтировать, оформить, проверить текст или собрать публикационный пакет."), ("Подготовка данных", "Используйте понятные имена файлов, качественные исходники и точное описание задачи."), ("Проверка результата", "Перед публикацией проверьте preview, текст, тайминги, формат и качество файла.")]),
            ("3. Оплата, доступ и лимиты", ["Платный доступ активируется автоматически после успешной онлайн-оплаты.", "План может включать срок доступа, объём хранилища, лимиты файлов, доступные инструменты и приоритет обработки."], [("Активация", "Доступ обычно появляется в аккаунте сразу после подтверждения платежа."), ("Лимиты", "Лимиты зависят от выбранного плана и действующих правил сервиса."), ("Доставка", "Физическая доставка не используется; файлы предоставляются цифровым способом.")]),
            ("4. Подготовка файлов", ["Качественные исходные материалы улучшают результат и уменьшают необходимость повторной обработки.", "Перед загрузкой проверьте формат, размер, язык, пропорции, качество звука и требования платформы."], [("Видео", "Проверьте длительность, ориентацию, разрешение и требования площадки."), ("Дизайн", "Подготовьте заголовок, брендовые цвета, референсы и нужные размеры."), ("Документы", "Используйте DOCX, PDF или TXT, если формат поддерживается, и уберите лишние личные данные.")]),
            ("5. Проверка результата", ["Перед публикацией всегда откройте preview или скачанный файл и проверьте результат вручную.", "AI-assisted инструменты ускоряют подготовку, но финальное утверждение остаётся ответственностью клиента."], [("Текст", "Проверьте орфографию, имена, ссылки, даты, цены и контакты."), ("Медиа", "Проверьте резкость, кадрирование, звук, субтитры и качество экспорта."), ("Повтор", "Если нужны правки, запустите повторную обработку или создайте новую задачу с уточнёнными данными.")]),
            ("6. Поддержка и решение проблем", ["При обращении в поддержку укажите email аккаунта, дату оплаты, название плана, название задачи, скриншоты и краткое описание проблемы.", "Если загрузка или обработка не проходит, проверьте размер, формат, соединение и обновите страницу."], [("Проблема с оплатой", "Отправьте дату платежа, сумму, email аккаунта и подтверждение оплаты."), ("Файл не загружается", "Попробуйте поддерживаемый формат, короткое имя файла и стабильное соединение."), ("Нет результата", "Проверьте статус задачи; сложные файлы могут обрабатываться дольше.")]),
            ("7. Обучающие видео и примеры работы", ["В этом разделе публикуются короткие уроки по основным сценариям CherryX Creator Studio.", "Уроки помогают понять навигацию в workspace, оплату, скачивание и подготовку материалов к публикации."], [("Быстрый старт", "Как открыть workspace, выбрать инструмент и запустить первую задачу."), ("Оплата", "Как активируется доступ, где смотреть лимиты и где скачивать готовые файлы."), ("Публикация", "Как связаны обложки, субтитры и ZIP-пакеты.")]),
            ("8. Видео-редактор", ["Видео-редактор используется для подготовки роликов, коротких клипов и материалов перед публикацией.", "Он подходит, когда важны кадрирование, порядок фрагментов, preview, синхронизация звука и финальный экспорт."], [("Импорт", "Загрузите исходное видео и дождитесь готовности preview."), ("Монтаж", "Работайте со сценами, порядком, кадрированием и визуальной логикой ролика."), ("Экспорт", "Скачайте финальный файл и проверьте его локально перед публикацией.")]),
            ("9. Музыкальный редактор", ["Музыкальный редактор помогает подготавливать аудио для видео, превью и публикационных задач.", "Используйте только аудио, на которое у вас есть права, особенно для публичных платформ."], [("Загрузка аудио", "Добавьте исходную дорожку и проверьте, что она корректно открывается."), ("Подготовка", "Проверьте громкость, длительность, начало, окончание и важные акценты."), ("Права", "Перед публикацией убедитесь, что вы можете использовать музыку или аудио-фрагмент.")]),
            ("10. Дизайн-доска и проекты", ["Дизайн-доска — рабочее пространство для обложек, превью, баннеров, макетов и визуальных ассетов.", "Дизайн-проекты помогают хранить отдельные креативные задачи организованно и возвращаться к ним позже."], [("Проекты", "Создавайте отдельный проект под каждую обложку, preview, баннер или макет."), ("Элементы", "Следите, чтобы текст и изображения не перекрывали важные зоны."), ("Экспорт", "Скачайте PNG, JPG или WEBP и проверьте читаемость на мобильном экране.")]),
            ("11. Проверка уникальности, документов и текстов", ["Раздел проверки помогает анализировать тексты, документы, черновики и статьи на уникальность, повторы и AI-risk признаки.", "Результат является аналитическим ориентиром, а не юридическим, академическим или редакционным заключением."], [("Текст", "Вставьте текст для быстрой проверки структуры, повторов и возможных AI-признаков."), ("Документы", "Загружайте поддерживаемые DOCX, PDF или TXT в пределах лимита размера."), ("Отчёт", "Используйте отчёт как чек-лист: переписать слабые места, добавить источники и проверить факты.")]),
            ("12. Пакет публикации", ["Пакет публикации помогает собрать финальные материалы: ZIP, превью, тексты, обложки, субтитры и связанные файлы.", "Это удобно, когда набор нужно передать клиенту, монтажёру, дизайнеру или человеку, который публикует контент."], [("Состав", "Проверьте, какие файлы должны войти в ZIP перед скачиванием."), ("Имена файлов", "Используйте понятные финальные названия, чтобы каждый ассет легко находился."), ("Финальная проверка", "Откройте архив перед отправкой или публикацией.")]),
        ],
        "videos_title": "Обучающие видео",
        "videos_copy": "Здесь появляются короткие уроки по работе с сервисом: первый запуск, оплата, скачивание и публикационный workflow.",
        "videos": [
            ("Быстрый старт", "Откройте workspace, выберите инструмент и запустите первую задачу.", ""),
            ("Оплата и скачивание", "Разберитесь с активацией доступа, лимитами и готовыми файлами.", ""),
            ("Публикационный workflow", "Подготовьте обложки, субтитры и ZIP-пакеты для публикации.", ""),
        ],
        "faq": [
            ("Где появляются готовые файлы?", "В карточке задачи внутри рабочего пространства. После завершения доступны кнопки открытия и скачивания."),
            ("Нужна ли физическая доставка?", "Нет. CherryX Creator Studio предоставляет только цифровые услуги."),
            ("Где смотреть обучающие видео?", "Откройте раздел обучающих видео. Когда урок доступен, его можно посмотреть прямо в документации."),
            ("Можно ли работать только с видео?", "Да. Можно использовать видео-редактор или видео-задачу без обложек и субтитров."),
            ("Можно ли отдельно подготовить музыку?", "Да. Музыкальный редактор можно использовать как отдельный инструмент для аудио."),
            ("Что такое дизайн-доска?", "Это рабочее пространство для визуальных проектов: обложек, превью, баннеров и макетов."),
            ("Проверка уникальности даёт окончательное заключение?", "Нет. Это аналитический ориентир; юридические, академические и редакционные выводы проверяются отдельно."),
            ("Можно ли проверять PDF и DOCX?", "Да, если инструмент поддерживает формат и файл не превышает лимит."),
            ("Что делать, если AI-risk высокий?", "Перечитайте текст, добавьте источники, конкретику и перепишите повторяющиеся шаблонные фразы."),
            ("Как готовить материалы для публикации?", "Соберите финальные версии, используйте понятные имена, скачайте ZIP и проверьте архив."),
            ("Что отправить в поддержку?", "Email аккаунта, дату оплаты, название задачи, скриншоты и краткое описание проблемы."),
        ],
    },
}


DOCS_CONTENT["uk"] = {
    "label": "Документація та навчання",
    "title": "Документація CherryX Creator Studio",
    "description": "Практичний посібник для клієнтів: вибрати інструмент, оплатити доступ, завантажити файли, підготувати контент і скачати готові цифрові результати.",
    "seo": "Документація CherryX Creator Studio: відеоредактор, музичний редактор, дизайн-дошка, перевірка унікальності, обкладинки, субтитри, PDF-резюме, пакети публікації, оплата і завантаження.",
    "quick": [("Старт", "Оберіть план або інструмент і відкрийте workspace."), ("Завантаження", "Додайте файли, текст, медіа, посилання або опис задачі."), ("Обробка", "Запустіть задачу, перевірте preview і стежте за прогресом."), ("Скачування", "Відкрийте завершену задачу і скачайте готові файли.")],
    "sections": [
        ("1. Що таке CherryX Creator Studio", ["CherryX Creator Studio — дистанційний цифровий сервіс для створення, обробки та підготовки креативних файлів.", "Сервіс працює з відео, обкладинками, субтитрами, PDF-резюме, дизайн-макетами, текстами, музикою та пакетами публікації."], [("Цифровий формат", "Усі результати надаються онлайн у workspace."), ("Інструменти", "Конвертер, Shorts, обкладинки, субтитри, резюме, дизайн, відео, музика та перевірка унікальності."), ("Для кого", "Для creators, студій, фрилансерів і клієнтів, яким потрібні готові цифрові матеріали.")]),
        ("2. Основний сценарій роботи", ["Оберіть інструмент під задачу, завантажте матеріали та перевірте налаштування перед обробкою.", "Коли задача завершиться, відкрийте її картку, перевірте preview і скачайте доступні результати."], [("Вибір інструмента", "Починайте з цілі: конвертація, монтаж, дизайн, перевірка тексту або пакет публікації."), ("Підготовка даних", "Використовуйте зрозумілі назви файлів, якісні джерела та точний опис."), ("Перевірка", "Перед публікацією перевірте preview, текст, таймінги, формат і якість.")]),
        ("3. Оплата, доступ і ліміти", ["Платний доступ активується автоматично після успішної онлайн-оплати.", "План може включати строк доступу, сховище, ліміти файлів, доступні інструменти та пріоритет обробки."], [("Активація", "Доступ зазвичай з'являється одразу після підтвердження платежу."), ("Ліміти", "Ліміти залежать від обраного плану та правил сервісу."), ("Доставка", "Фізична доставка не використовується; файли надаються цифрово.")]),
        ("4. Підготовка файлів", ["Якісні вихідні матеріали покращують результат і зменшують повторну обробку.", "Перед завантаженням перевірте формат, розмір, мову, пропорції, звук і вимоги платформи."], [("Відео", "Перевірте тривалість, орієнтацію, роздільність і вимоги майданчика."), ("Дизайн", "Підготуйте заголовок, бренд-кольори, референси та потрібні розміри."), ("Документи", "Використовуйте DOCX, PDF або TXT, якщо формат підтримується.")]),
        ("5. Перевірка результату", ["Перед публікацією відкрийте preview або скачаний файл і перевірте результат вручну.", "AI-assisted інструменти пришвидшують підготовку, але фінальне рішення залишається за клієнтом."], [("Текст", "Перевірте орфографію, імена, посилання, дати, ціни та контакти."), ("Медіа", "Перевірте різкість, кадрування, звук, субтитри та якість експорту."), ("Повтор", "Якщо потрібні правки, запустіть повторну обробку або створіть нову задачу.")]),
        ("6. Підтримка та проблеми", ["Для підтримки вкажіть email акаунта, дату оплати, назву плану, назву задачі, скриншоти і короткий опис.", "Якщо завантаження або обробка не працює, перевірте розмір, формат, з'єднання та оновіть сторінку."], [("Оплата", "Надішліть дату платежу, суму, email і підтвердження."), ("Завантаження", "Спробуйте підтримуваний формат, коротшу назву файлу та стабільне з'єднання."), ("Немає результату", "Перевірте статус задачі; складні файли можуть оброблятися довше.")]),
        ("7. Навчальні відео та приклади", ["У цьому розділі публікуються короткі уроки щодо основних сценаріїв CherryX Creator Studio.", "Уроки допомагають зрозуміти workspace, оплату, скачування та підготовку до публікації."], [("Швидкий старт", "Як відкрити workspace, вибрати інструмент і запустити першу задачу."), ("Оплата", "Як активується доступ, де дивитися ліміти і де скачувати файли."), ("Публікація", "Як пов'язані обкладинки, субтитри та ZIP-пакети.")]),
        ("8. Відеоредактор", ["Відеоредактор використовується для підготовки роликів, коротких кліпів і матеріалів перед публікацією.", "Він корисний, коли важливі кадрування, порядок фрагментів, preview, звук і фінальний експорт."], [("Імпорт", "Завантажте відео і дочекайтеся preview."), ("Монтаж", "Працюйте зі сценами, порядком, кадруванням і логікою ролика."), ("Експорт", "Скачайте фінальний файл і перевірте його перед публікацією.")]),
        ("9. Музичний редактор", ["Музичний редактор допомагає підготувати аудіо для відео, preview і публікацій.", "Використовуйте лише аудіо, на яке маєте права, особливо для публічних платформ."], [("Завантаження аудіо", "Додайте доріжку і перевірте, що вона відкривається коректно."), ("Підготовка", "Перевірте гучність, тривалість, початок, кінець і акценти."), ("Права", "Перед публікацією переконайтеся, що можете використовувати музику.")]),
        ("10. Дизайн-дошка і проєкти", ["Дизайн-дошка — workspace для обкладинок, preview, банерів, макетів і візуальних ассетів.", "Дизайн-проєкти допомагають зберігати окремі креативні задачі організовано."], [("Проєкти", "Створюйте окремий проєкт під кожну обкладинку, preview, банер або макет."), ("Елементи", "Стежте, щоб текст і зображення не перекривали важливі зони."), ("Експорт", "Скачайте PNG, JPG або WEBP і перевірте читабельність на телефоні.")]),
        ("11. Перевірка унікальності, документів і текстів", ["Розділ перевірки допомагає аналізувати тексти, документи, чернетки та статті на унікальність, повтори й AI-risk.", "Результат є аналітичним орієнтиром, а не юридичним, академічним чи редакційним висновком."], [("Текст", "Вставте текст для швидкої перевірки структури, повторів і можливих AI-ознак."), ("Документи", "Завантажуйте підтримувані DOCX, PDF або TXT у межах ліміту."), ("Звіт", "Використовуйте звіт як чек-лист для редагування, джерел і перевірки фактів.")]),
        ("12. Пакет публікації", ["Пакет публікації допомагає зібрати фінальні матеріали: ZIP, preview, тексти, обкладинки, субтитри та пов'язані файли.", "Це зручно для передачі матеріалів клієнту, монтажеру, дизайнеру або публікатору."], [("Склад", "Перевірте, які файли мають увійти до ZIP перед скачуванням."), ("Назви файлів", "Використовуйте зрозумілі фінальні назви."), ("Фінальна перевірка", "Відкрийте архів перед відправкою або публікацією.")]),
    ],
    "videos_title": "Навчальні відео",
    "videos_copy": "Тут з'являються короткі уроки: перший запуск, оплата, скачування і публікаційний workflow.",
    "videos": [("Швидкий старт", "Відкрийте workspace, оберіть інструмент і запустіть першу задачу.", ""), ("Оплата і скачування", "Розберіться з активацією доступу, лімітами та готовими файлами.", ""), ("Публікаційний workflow", "Підготуйте обкладинки, субтитри та ZIP-пакети.", "")],
    "faq": [("Де з'являються готові файли?", "У картці задачі всередині workspace."), ("Чи потрібна фізична доставка?", "Ні. Сервіс надає лише цифрові послуги."), ("Де дивитися навчальні відео?", "Відкрийте розділ навчальних відео; доступні уроки переглядаються прямо в документації."), ("Чи можна працювати тільки з відео?", "Так, можна використовувати відеоредактор без обкладинок і субтитрів."), ("Чи можна окремо підготувати музику?", "Так, музичний редактор можна використовувати окремо."), ("Що таке дизайн-дошка?", "Це workspace для обкладинок, preview, банерів і макетів."), ("Перевірка унікальності остаточна?", "Ні, це аналітичний орієнтир."), ("Чи можна перевіряти PDF і DOCX?", "Так, якщо формат підтримується і файл у межах ліміту."), ("Що робити при високому AI-risk?", "Додайте джерела, конкретику і перепишіть шаблонні фрази."), ("Як підготувати матеріали до публікації?", "Зберіть фінальні версії, назвіть файли зрозуміло, скачайте ZIP і перевірте його."), ("Що надсилати в підтримку?", "Email, дату оплати, назву задачі, скриншоти і короткий опис.")],
}


DOCS_CONTENT["fr"] = {
    **DOCS_CONTENT["en"],
    "label": "Documentation et formation",
    "title": "Documentation CherryX Creator Studio",
    "description": "Guide pratique pour les clients : choisir un outil, payer l'accès, téléverser des fichiers, préparer le contenu et télécharger les résultats numériques.",
    "seo": "Documentation CherryX Creator Studio : éditeur vidéo, éditeur musique, tableau design, contrôle d'originalité, couvertures, sous-titres, CV PDF, packs de publication, paiement et téléchargements.",
    "quick": [("Démarrer", "Choisissez un plan ou un outil et ouvrez l'espace de travail."), ("Téléverser", "Ajoutez fichiers, texte, médias, liens ou détails de tâche."), ("Traiter", "Lancez la tâche, vérifiez l'aperçu et suivez la progression."), ("Télécharger", "Ouvrez la tâche terminée et téléchargez les fichiers.")],
    "sections": [
        ("1. Qu'est-ce que CherryX Creator Studio", ["CherryX Creator Studio est un service numérique à distance pour créer, traiter et préparer des fichiers créatifs.", "Le service couvre vidéos, couvertures, sous-titres, CV PDF, maquettes, textes, musique et packs de publication."], [("Numérique uniquement", "Tous les résultats sont livrés en ligne dans l'espace de travail."), ("Outils", "Convertisseur, Shorts, couvertures, sous-titres, CV, design, vidéo, musique et contrôle d'originalité."), ("Pour qui", "Créateurs, studios, freelances et clients qui ont besoin de fichiers prêts.")]),
        ("2. Flux de travail principal", ["Choisissez l'outil adapté, téléversez les sources et vérifiez les réglages.", "Une fois la tâche terminée, ouvrez sa carte pour vérifier et télécharger les résultats."], [("Choisir", "Partez de l'objectif : convertir, monter, designer, vérifier un texte ou créer un pack."), ("Préparer", "Utilisez des noms clairs, de bonnes sources et une demande précise."), ("Vérifier", "Contrôlez aperçu, texte, timing, format et qualité.")]),
        ("3. Paiement, accès et limites", ["L'accès payant s'active automatiquement après le paiement en ligne réussi.", "Les plans peuvent inclure durée d'accès, stockage, limites, outils et priorité."], [("Activation", "L'accès apparaît normalement juste après confirmation du paiement."), ("Limites", "Les limites dépendent du plan choisi et des règles du service."), ("Livraison", "Aucune livraison physique ; les fichiers sont fournis numériquement.")]),
        ("4. Préparation des fichiers", ["De bonnes sources améliorent le résultat et réduisent les reprises.", "Vérifiez format, taille, langue, ratio, son et exigences de plateforme."], [("Vidéo", "Vérifiez durée, orientation, résolution et exigences de publication."), ("Design", "Préparez titre, couleurs de marque, références et dimensions."), ("Documents", "Utilisez DOCX, PDF ou TXT si le format est pris en charge.")]),
        ("5. Vérification du résultat", ["Avant publication, ouvrez toujours l'aperçu ou le fichier téléchargé.", "Les outils assistés par IA accélèrent le travail, mais la validation finale revient au client."], [("Texte", "Vérifiez orthographe, noms, liens, dates, prix et contacts."), ("Médias", "Vérifiez netteté, cadrage, audio, sous-titres et export."), ("Reprise", "Relancez la tâche ou créez-en une nouvelle avec des données plus précises.")]),
        ("6. Support et dépannage", ["Pour le support, envoyez email du compte, date de paiement, plan, tâche, captures et description.", "En cas d'échec, vérifiez taille, format, connexion et actualisez la page."], [("Paiement", "Indiquez date, montant, email et confirmation."), ("Upload", "Essayez un format compatible, un nom plus court et une connexion stable."), ("Résultat absent", "Vérifiez le statut ; les fichiers complexes peuvent prendre plus de temps.")]),
        ("7. Vidéos de formation et exemples", ["Cette section contient de courtes leçons sur les scénarios principaux.", "Elles expliquent l'espace de travail, paiement, téléchargements et préparation à la publication."], [("Démarrage rapide", "Ouvrir l'espace, choisir un outil et lancer la première tâche."), ("Paiement", "Comprendre activation, limites et téléchargements."), ("Publication", "Relier couvertures, sous-titres et packs ZIP.")]),
        ("8. Éditeur vidéo", ["L'éditeur vidéo sert à préparer clips courts et médias prêts à publier.", "Il est utile pour cadrage, ordre, aperçu, audio et export final."], [("Import", "Téléversez la vidéo et attendez l'aperçu."), ("Montage", "Travaillez scènes, ordre, cadrage et logique visuelle."), ("Export", "Téléchargez le fichier final et vérifiez-le avant publication.")]),
        ("9. Éditeur musique", ["L'éditeur musique prépare les éléments audio pour vidéos et publications.", "Utilisez uniquement des audios dont vous avez les droits."], [("Audio", "Ajoutez la piste et vérifiez qu'elle s'ouvre."), ("Préparation", "Contrôlez volume, durée, début, fin et accents."), ("Droits", "Confirmez vos droits avant publication.")]),
        ("10. Tableau design et projets", ["Le tableau design sert aux couvertures, aperçus, bannières, maquettes et assets visuels.", "Les projets gardent les tâches créatives séparées et organisées."], [("Projets", "Créez un projet par couverture, aperçu, bannière ou maquette."), ("Éléments", "Évitez que texte ou images masquent les zones importantes."), ("Export", "Téléchargez PNG, JPG ou WEBP et vérifiez la lisibilité mobile.")]),
        ("11. Originalité, documents et textes", ["Le contrôle aide à analyser textes, documents, brouillons et articles pour originalité, répétitions et AI-risk.", "Le résultat est un repère analytique, pas une décision juridique, académique ou éditoriale."], [("Texte", "Collez un texte pour vérifier structure et répétitions."), ("Documents", "Téléversez DOCX, PDF ou TXT compatibles dans la limite."), ("Rapport", "Utilisez le rapport comme checklist de réécriture et vérification.")]),
        ("12. Pack de publication", ["Le pack rassemble ZIP, aperçu, textes, couvertures, sous-titres et fichiers liés.", "Pratique pour transmettre les matériaux à un client, monteur, designer ou éditeur."], [("Contenu", "Vérifiez les fichiers à inclure avant le ZIP."), ("Noms", "Utilisez des noms finaux clairs."), ("Contrôle final", "Ouvrez l'archive avant envoi ou publication.")]),
    ],
    "videos_title": "Vidéos de formation",
    "videos_copy": "De courtes leçons apparaissent ici : premier lancement, paiement, téléchargement et flux de publication.",
    "videos": [("Démarrage rapide", "Ouvrez l'espace, choisissez un outil et lancez une tâche.", ""), ("Paiement et téléchargements", "Comprendre accès, limites et fichiers prêts.", ""), ("Flux de publication", "Préparer couvertures, sous-titres et ZIP.", "")],
    "faq": [("Où sont les fichiers ?", "Dans la carte de tâche de l'espace de travail."), ("Y a-t-il une livraison physique ?", "Non, les services sont numériques."), ("Où regarder les vidéos ?", "Dans la section vidéos de formation."), ("Puis-je travailler seulement la vidéo ?", "Oui, sans couvertures ni sous-titres."), ("Puis-je préparer la musique séparément ?", "Oui, avec l'éditeur musique."), ("Qu'est-ce que le tableau design ?", "Un espace pour couvertures, aperçus, bannières et maquettes."), ("Le contrôle d'originalité est-il final ?", "Non, c'est un repère analytique."), ("PDF et DOCX sont-ils acceptés ?", "Oui, si le format et la taille sont pris en charge."), ("Que faire si AI-risk est élevé ?", "Ajoutez sources, détails et reformulez les phrases répétitives."), ("Comment préparer la publication ?", "Rassemblez les versions finales, nommez clairement, téléchargez et vérifiez le ZIP."), ("Qu'envoyer au support ?", "Email, date de paiement, tâche, captures et description.")],
}


DOCS_CONTENT["de"] = {
    **DOCS_CONTENT["fr"],
    "label": "Dokumentation und Schulung",
    "title": "CherryX Creator Studio Dokumentation",
    "description": "Praktischer Kundenleitfaden: Tool wählen, Zugang bezahlen, Dateien hochladen, Inhalte vorbereiten und digitale Ergebnisse herunterladen.",
    "quick": [("Start", "Plan oder Tool wählen und Workspace öffnen."), ("Upload", "Dateien, Text, Medien, Links oder Aufgabendetails hinzufügen."), ("Verarbeiten", "Aufgabe starten, Vorschau prüfen und Fortschritt verfolgen."), ("Download", "Abgeschlossene Aufgabe öffnen und Dateien herunterladen.")],
    "sections": [(s[0].replace("Qu'est-ce que", "Was ist").replace("Flux de travail principal", "Hauptworkflow").replace("Paiement, accès et limites", "Zahlung, Zugang und Limits").replace("Préparation des fichiers", "Dateivorbereitung").replace("Vérification du résultat", "Ergebnis prüfen").replace("Support et dépannage", "Support und Fehlerbehebung").replace("Vidéos de formation et exemples", "Schulungsvideos und Beispiele").replace("Éditeur vidéo", "Videoeditor").replace("Éditeur musique", "Musikeditor").replace("Tableau design et projets", "Design-Board und Projekte").replace("Originalité, documents et textes", "Originalität, Dokumente und Texte").replace("Pack de publication", "Publikationspaket"), s[1], s[2]) for s in DOCS_CONTENT["fr"]["sections"]],
    "videos_title": "Schulungsvideos",
    "videos_copy": "Kurze Lektionen erscheinen hier: erster Start, Zahlung, Downloads und Veröffentlichungsworkflow.",
    "videos": [("Schnellstart", "Workspace öffnen, Tool wählen und erste Aufgabe starten.", ""), ("Zahlung und Downloads", "Zugang, Limits und fertige Dateien verstehen.", ""), ("Veröffentlichungsworkflow", "Cover, Untertitel und ZIP-Pakete vorbereiten.", "")],
    "faq": [("Wo sind meine Dateien?", "In der Aufgabenkarte im Workspace."), ("Gibt es physische Lieferung?", "Nein, die Dienste sind digital."), ("Wo sehe ich Schulungsvideos?", "Im Bereich Schulungsvideos dieser Dokumentation."), ("Kann ich nur mit Video arbeiten?", "Ja, ohne Cover oder Untertitel."), ("Kann ich Musik separat vorbereiten?", "Ja, mit dem Musikeditor."), ("Was ist das Design-Board?", "Ein Workspace für Cover, Vorschauen, Banner und Layouts."), ("Ist die Originalitätsprüfung endgültig?", "Nein, sie ist ein analytischer Hinweis."), ("Kann ich PDF und DOCX prüfen?", "Ja, wenn Format und Größe unterstützt werden."), ("Was tun bei hohem AI-risk?", "Quellen, konkrete Details und eigene Formulierungen ergänzen."), ("Wie bereite ich Veröffentlichung vor?", "Finale Dateien sammeln, klar benennen, ZIP laden und prüfen."), ("Was sende ich dem Support?", "Email, Zahlungsdatum, Aufgabe, Screenshots und Beschreibung.")],
}


DOCS_CONTENT["es"] = {
    **DOCS_CONTENT["fr"],
    "label": "Documentación y formación",
    "title": "Documentación de CherryX Creator Studio",
    "description": "Guía práctica para clientes: elegir herramienta, pagar acceso, subir archivos, preparar contenido y descargar resultados digitales.",
    "quick": [("Inicio", "Elige un plan o herramienta y abre el espacio de trabajo."), ("Subir", "Añade archivos, texto, medios, enlaces o detalles."), ("Procesar", "Ejecuta la tarea, revisa la vista previa y sigue el progreso."), ("Descargar", "Abre la tarea terminada y descarga los archivos.")],
    "sections": [(s[0].replace("Qu'est-ce que", "Qué es").replace("Flux de travail principal", "Flujo principal").replace("Paiement, accès et limites", "Pago, acceso y límites").replace("Préparation des fichiers", "Preparación de archivos").replace("Vérification du résultat", "Revisión del resultado").replace("Support et dépannage", "Soporte y solución de problemas").replace("Vidéos de formation et exemples", "Videos formativos y ejemplos").replace("Éditeur vidéo", "Editor de video").replace("Éditeur musique", "Editor de música").replace("Tableau design et projets", "Mesa de diseño y proyectos").replace("Originalité, documents et textes", "Originalidad, documentos y textos").replace("Pack de publication", "Paquete de publicación"), s[1], s[2]) for s in DOCS_CONTENT["fr"]["sections"]],
    "videos_title": "Videos formativos",
    "videos_copy": "Aquí aparecen lecciones cortas: primer inicio, pago, descargas y flujo de publicación.",
    "videos": [("Inicio rápido", "Abre el espacio, elige una herramienta y ejecuta la primera tarea.", ""), ("Pago y descargas", "Entiende acceso, límites y archivos listos.", ""), ("Flujo de publicación", "Prepara portadas, subtítulos y paquetes ZIP.", "")],
    "faq": [("¿Dónde están mis archivos?", "En la tarjeta de tarea del espacio de trabajo."), ("¿Hay entrega física?", "No, los servicios son digitales."), ("¿Dónde ver los videos?", "En la sección de videos formativos."), ("¿Puedo trabajar solo con video?", "Sí, sin portadas ni subtítulos."), ("¿Puedo preparar música aparte?", "Sí, con el editor de música."), ("¿Qué es la mesa de diseño?", "Un espacio para portadas, previews, banners y diseños."), ("¿La comprobación de originalidad es final?", "No, es una guía analítica."), ("¿Puedo revisar PDF y DOCX?", "Sí, si el formato y tamaño son compatibles."), ("¿Qué hacer con AI-risk alto?", "Añade fuentes, detalles concretos y reformula frases repetidas."), ("¿Cómo preparar publicación?", "Reúne versiones finales, nombra claro, descarga y revisa el ZIP."), ("¿Qué enviar a soporte?", "Email, fecha de pago, tarea, capturas y descripción.")],
}


DOCS_CONTENT["it"] = {
    **DOCS_CONTENT["fr"],
    "label": "Documentazione e formazione",
    "title": "Documentazione CherryX Creator Studio",
    "description": "Guida pratica per clienti: scegliere uno strumento, pagare l'accesso, caricare file, preparare contenuti e scaricare risultati digitali.",
    "quick": [("Inizio", "Scegli piano o strumento e apri il workspace."), ("Carica", "Aggiungi file, testo, media, link o dettagli."), ("Elabora", "Avvia l'attività, controlla l'anteprima e segui lo stato."), ("Scarica", "Apri l'attività completata e scarica i file.")],
    "sections": [(s[0].replace("Qu'est-ce que", "Che cos'è").replace("Flux de travail principal", "Flusso principale").replace("Paiement, accès et limites", "Pagamento, accesso e limiti").replace("Préparation des fichiers", "Preparazione file").replace("Vérification du résultat", "Controllo del risultato").replace("Support et dépannage", "Supporto e problemi").replace("Vidéos de formation et exemples", "Video formativi ed esempi").replace("Éditeur vidéo", "Editor video").replace("Éditeur musique", "Editor musicale").replace("Tableau design et projets", "Board design e progetti").replace("Originalité, documents et textes", "Originalità, documenti e testi").replace("Pack de publication", "Pacchetto pubblicazione"), s[1], s[2]) for s in DOCS_CONTENT["fr"]["sections"]],
    "videos_title": "Video formativi",
    "videos_copy": "Qui appaiono brevi lezioni: primo avvio, pagamento, download e flusso di pubblicazione.",
    "videos": [("Avvio rapido", "Apri il workspace, scegli uno strumento e avvia la prima attività.", ""), ("Pagamento e download", "Comprendi accesso, limiti e file pronti.", ""), ("Flusso pubblicazione", "Prepara copertine, sottotitoli e pacchetti ZIP.", "")],
    "faq": [("Dove sono i file?", "Nella scheda attività del workspace."), ("C'è consegna fisica?", "No, i servizi sono digitali."), ("Dove guardare i video?", "Nella sezione video formativi."), ("Posso lavorare solo con video?", "Sì, senza copertine o sottotitoli."), ("Posso preparare musica separatamente?", "Sì, con l'editor musicale."), ("Cos'è la board design?", "Uno spazio per copertine, anteprime, banner e layout."), ("Il controllo originalità è definitivo?", "No, è una guida analitica."), ("Posso controllare PDF e DOCX?", "Sì, se formato e dimensione sono supportati."), ("Cosa fare con AI-risk alto?", "Aggiungi fonti, dettagli concreti e riscrivi frasi ripetitive."), ("Come preparare la pubblicazione?", "Raccogli versioni finali, nomina chiaramente, scarica e controlla ZIP."), ("Cosa inviare al supporto?", "Email, data pagamento, attività, screenshot e descrizione.")],
}


DOCS_CONTENT["ka"] = {
    **DOCS_CONTENT["en"],
    "label": "დოკუმენტაცია და სწავლება",
    "title": "CherryX Creator Studio დოკუმენტაცია",
    "description": "პრაქტიკული სახელმძღვანელო კლიენტებისთვის: აირჩიეთ ინსტრუმენტი, გადაიხადეთ წვდომა, ატვირთეთ ფაილები, მოამზადეთ კონტენტი და ჩამოტვირთეთ ციფრული შედეგები.",
    "quick": [("სტარტი", "აირჩიეთ გეგმა ან ინსტრუმენტი და გახსენით workspace."), ("ატვირთვა", "დაამატეთ ფაილები, ტექსტი, მედია, ბმულები ან ამოცანის აღწერა."), ("დამუშავება", "გაუშვით ამოცანა, შეამოწმეთ preview და პროგრესი."), ("ჩამოტვირთვა", "გახსენით დასრულებული ამოცანა და ჩამოტვირთეთ ფაილები.")],
    "videos_title": "სასწავლო ვიდეოები",
    "videos_copy": "აქ გამოჩნდება მოკლე გაკვეთილები: პირველი გაშვება, გადახდა, ჩამოტვირთვა და პუბლიკაციის workflow.",
    "videos": [("სწრაფი სტარტი", "გახსენით workspace, აირჩიეთ ინსტრუმენტი და გაუშვით პირველი ამოცანა.", ""), ("გადახდა და ჩამოტვირთვა", "გაიგეთ წვდომა, ლიმიტები და მზად ფაილები.", ""), ("პუბლიკაციის workflow", "მოამზადეთ ქავერები, სუბტიტრები და ZIP პაკეტები.", "")],
    "faq": [("სად არის ფაილები?", "workspace-ის ამოცანის ბარათში."), ("არსებობს ფიზიკური მიწოდება?", "არა, სერვისები მხოლოდ ციფრულია."), ("სად ვნახო სასწავლო ვიდეოები?", "სასწავლო ვიდეოების განყოფილებაში."), ("შეიძლება მხოლოდ ვიდეოზე მუშაობა?", "დიახ, ქავერებისა და სუბტიტრების გარეშე."), ("შეიძლება მუსიკის ცალკე მომზადება?", "დიახ, მუსიკის რედაქტორით."), ("რა არის დიზაინ-დაფა?", "workspace ქავერებისთვის, preview-ებისთვის, ბანერებისა და მაკეტებისთვის."), ("ორიგინალობის შემოწმება საბოლოოა?", "არა, ეს ანალიტიკური ორიენტირია."), ("PDF და DOCX მოწმდება?", "დიახ, თუ ფორმატი და ზომა მხარდაჭერილია."), ("რა ვქნა მაღალი AI-risk-ისას?", "დაამატეთ წყაროები, კონკრეტიკა და გადააწერეთ შაბლონური ფრაზები."), ("როგორ მოვამზადო პუბლიკაცია?", "შეაგროვეთ საბოლოო ფაილები, დაარქვით გასაგებად, ჩამოტვირთეთ და შეამოწმეთ ZIP."), ("რა გავუგზავნო მხარდაჭერას?", "Email, გადახდის თარიღი, ამოცანა, screenshot-ები და აღწერა.")],
}


DOCS_CONTENT["hy"] = {
    **DOCS_CONTENT["en"],
    "label": "Փաստաթղթեր և ուսուցում",
    "title": "CherryX Creator Studio փաստաթղթեր",
    "description": "Գործնական ուղեցույց հաճախորդների համար՝ ընտրել գործիք, վճարել հասանելիության համար, վերբեռնել ֆայլեր, պատրաստել բովանդակություն և ներբեռնել թվային արդյունքներ։",
    "quick": [("Սկիզբ", "Ընտրեք պլան կամ գործիք և բացեք workspace-ը։"), ("Վերբեռնում", "Ավելացրեք ֆայլեր, տեքստ, մեդիա, հղումներ կամ առաջադրանքի նկարագրություն։"), ("Մշակում", "Գործարկեք առաջադրանքը, ստուգեք preview-ն և առաջընթացը։"), ("Ներբեռնում", "Բացեք ավարտված առաջադրանքը և ներբեռնեք ֆայլերը։")],
    "videos_title": "Ուսուցողական տեսանյութեր",
    "videos_copy": "Այստեղ կհայտնվեն կարճ դասեր՝ առաջին գործարկում, վճարում, ներբեռնում և հրապարակման workflow։",
    "videos": [("Արագ սկիզբ", "Բացեք workspace-ը, ընտրեք գործիք և գործարկեք առաջին առաջադրանքը։", ""), ("Վճարում և ներբեռնում", "Հասկացեք հասանելիությունը, սահմանաչափերը և պատրաստ ֆայլերը։", ""), ("Հրապարակման workflow", "Պատրաստեք cover-ներ, ենթագրեր և ZIP փաթեթներ։", "")],
    "faq": [("Որտե՞ղ են ֆայլերը։", "workspace-ի առաջադրանքի քարտում։"), ("Կա՞ ֆիզիկական առաքում։", "Ոչ, ծառայությունները միայն թվային են։"), ("Որտե՞ղ դիտել ուսուցողական տեսանյութերը։", "Ուսուցողական տեսանյութերի բաժնում։"), ("Կարելի՞ է աշխատել միայն վիդեոյի հետ։", "Այո, առանց cover-ների և ենթագրերի։"), ("Կարելի՞ է երաժշտությունը պատրաստել առանձին։", "Այո, երաժշտական խմբագրիչով։"), ("Ի՞նչ է դիզայն-տախտակը։", "Workspace cover-ների, preview-ների, բաներների և layout-ների համար։"), ("Ունիկալության ստուգումը վերջնակա՞ն է։", "Ոչ, դա վերլուծական ուղեցույց է։"), ("Կարելի՞ է ստուգել PDF և DOCX։", "Այո, եթե ձևաչափը և չափը աջակցվում են։"), ("Ի՞նչ անել բարձր AI-risk-ի դեպքում։", "Ավելացրեք աղբյուրներ, կոնկրետություն և վերաշարադրեք կրկնվող արտահայտությունները։"), ("Ինչպե՞ս պատրաստել հրապարակումը։", "Հավաքեք վերջնական ֆայլերը, հստակ անվանեք, ներբեռնեք և ստուգեք ZIP-ը։"), ("Ի՞նչ ուղարկել աջակցությանը։", "Email, վճարման ամսաթիվ, առաջադրանք, սքրինշոթներ և նկարագրություն։")],
}


DOCS_CONTENT["de"].update({
    "seo": "CherryX Creator Studio Dokumentation: Videoeditor, Musikeditor, Design-Board, Originalitätsprüfung, Cover, Untertitel, PDF-Lebensläufe, Publikationspakete, Zahlung und Downloads.",
    "sections": [
        ("1. Was ist CherryX Creator Studio", ["CherryX Creator Studio ist ein digitaler Remote-Service zum Erstellen, Bearbeiten und Vorbereiten kreativer Dateien.", "Der Service arbeitet mit Videos, Covern, Untertiteln, PDF-Lebensläufen, Design-Layouts, Texten, Musik und Publikationspaketen."], [("Digitaler Service", "Alle Ergebnisse werden online im Workspace bereitgestellt."), ("Werkzeuge", "Konverter, Shorts, Cover, Untertitel, Lebenslauf, Design, Video, Musik und Originalitätsprüfung."), ("Für wen", "Für Creator, Studios, Freelancer und Kunden mit regelmäßigem Bedarf an digitalen Materialien.")]),
        ("2. Hauptworkflow", ["Wählen Sie das passende Werkzeug, laden Sie Ausgangsmaterialien hoch und prüfen Sie die Einstellungen.", "Nach Abschluss öffnen Sie die Aufgabenkarte, prüfen die Vorschau und laden die Ergebnisse herunter."], [("Werkzeug wählen", "Starten Sie mit dem Ziel: konvertieren, schneiden, gestalten, Text prüfen oder ein Paket sammeln."), ("Daten vorbereiten", "Nutzen Sie klare Dateinamen, gute Quellen und eine genaue Aufgabenbeschreibung."), ("Ergebnis prüfen", "Prüfen Sie Vorschau, Text, Timing, Format und Qualität.")]),
        ("3. Zahlung, Zugang und Limits", ["Bezahlter Zugang wird nach erfolgreicher Online-Zahlung automatisch aktiviert.", "Ein Plan kann Laufzeit, Speicher, Dateilimits, Werkzeuge und Bearbeitungspriorität enthalten."], [("Aktivierung", "Der Zugang erscheint normalerweise direkt nach Zahlungsbestätigung."), ("Limits", "Limits hängen vom gewählten Plan und den Serviceregeln ab."), ("Lieferung", "Es gibt keine physische Lieferung; Dateien werden digital bereitgestellt.")]),
        ("4. Dateivorbereitung", ["Gute Ausgangsdateien verbessern das Ergebnis und reduzieren Wiederholungen.", "Prüfen Sie Format, Größe, Sprache, Seitenverhältnis, Tonqualität und Plattformanforderungen."], [("Video", "Prüfen Sie Dauer, Ausrichtung, Auflösung und Veröffentlichungsanforderungen."), ("Design", "Bereiten Sie Titel, Markenfarben, Referenzen und Maße vor."), ("Dokumente", "Nutzen Sie DOCX, PDF oder TXT, wenn das Format unterstützt wird.")]),
        ("5. Ergebnis prüfen", ["Öffnen Sie vor der Veröffentlichung immer die Vorschau oder die heruntergeladene Datei.", "KI-gestützte Werkzeuge beschleunigen die Vorbereitung, die finale Freigabe bleibt beim Kunden."], [("Text", "Prüfen Sie Rechtschreibung, Namen, Links, Daten, Preise und Kontakte."), ("Medien", "Prüfen Sie Schärfe, Zuschnitt, Audio, Untertitel und Exportqualität."), ("Wiederholen", "Bei Korrekturen starten Sie die Aufgabe erneut oder erstellen eine neue Aufgabe.")]),
        ("6. Support und Fehlerbehebung", ["Für Support senden Sie Konto-Email, Zahlungsdatum, Plan, Aufgabenname, Screenshots und kurze Beschreibung.", "Wenn Upload oder Verarbeitung scheitert, prüfen Sie Größe, Format, Verbindung und aktualisieren Sie die Seite."], [("Zahlung", "Senden Sie Zahlungsdatum, Betrag, Email und Bestätigung."), ("Upload", "Probieren Sie ein unterstütztes Format, kürzeren Dateinamen und stabile Verbindung."), ("Kein Ergebnis", "Prüfen Sie den Status; komplexe Dateien können länger dauern.")]),
        ("7. Schulungsvideos und Beispiele", ["Hier erscheinen kurze Lektionen zu den wichtigsten CherryX Creator Studio Abläufen.", "Die Lektionen erklären Workspace, Zahlung, Downloads und Vorbereitung zur Veröffentlichung."], [("Schnellstart", "Workspace öffnen, Werkzeug wählen und erste Aufgabe starten."), ("Zahlung", "Aktivierung, Limits und Downloads verstehen."), ("Publikation", "Cover, Untertitel und ZIP-Pakete zusammendenken.")]),
        ("8. Videoeditor", ["Der Videoeditor dient zur Vorbereitung von Clips, Kurzvideos und publizierbaren Medien.", "Er ist hilfreich für Zuschnitt, Reihenfolge, Vorschau, Audio-Sync und finalen Export."], [("Import", "Video hochladen und auf die Vorschau warten."), ("Schnitt", "Mit Szenen, Reihenfolge, Zuschnitt und visueller Logik arbeiten."), ("Export", "Finale Datei laden und vor Veröffentlichung lokal prüfen.")]),
        ("9. Musikeditor", ["Der Musikeditor bereitet Audio für Videos, Vorschauen und Veröffentlichungen vor.", "Verwenden Sie nur Audio, für das Sie Nutzungsrechte haben."], [("Audio hochladen", "Spur hinzufügen und prüfen, ob sie korrekt geöffnet wird."), ("Vorbereiten", "Lautstärke, Dauer, Anfang, Ende und Akzente prüfen."), ("Rechte", "Vor Veröffentlichung Nutzungsrechte bestätigen.")]),
        ("10. Design-Board und Projekte", ["Das Design-Board ist ein Workspace für Cover, Vorschauen, Banner, Layouts und visuelle Assets.", "Design-Projekte halten einzelne kreative Aufgaben organisiert."], [("Projekte", "Für jedes Cover, Preview, Banner oder Layout ein Projekt anlegen."), ("Elemente", "Text und Bilder dürfen wichtige Bereiche nicht verdecken."), ("Export", "PNG, JPG oder WEBP laden und Lesbarkeit auf Mobilgeräten prüfen.")]),
        ("11. Originalität, Dokumente und Texte", ["Die Prüfung analysiert Texte, Dokumente, Entwürfe und Artikel auf Originalität, Wiederholungen und AI-risk.", "Das Ergebnis ist eine analytische Orientierung, kein rechtliches, akademisches oder redaktionelles Urteil."], [("Text", "Text einfügen und Struktur, Wiederholungen sowie mögliche KI-Muster prüfen."), ("Dokumente", "Unterstützte DOCX, PDF oder TXT innerhalb des Limits hochladen."), ("Bericht", "Als Checkliste für Überarbeitung, Quellen und Faktenprüfung nutzen.")]),
        ("12. Publikationspaket", ["Ein Publikationspaket sammelt ZIP, Vorschau, Texte, Cover, Untertitel und verbundene Dateien.", "Nützlich zur Übergabe an Kunden, Editor, Designer oder Publisher."], [("Inhalt", "Vor dem Download prüfen, welche Dateien in das ZIP gehören."), ("Dateinamen", "Klare finale Namen verwenden."), ("Finalcheck", "Archiv vor Versand oder Veröffentlichung öffnen.")]),
    ],
})

DOCS_CONTENT["es"].update({
    "seo": "Documentación de CherryX Creator Studio: editor de video, editor de música, mesa de diseño, comprobación de originalidad, portadas, subtítulos, CV PDF, paquetes de publicación, pagos y descargas.",
    "sections": [
        ("1. Qué es CherryX Creator Studio", ["CherryX Creator Studio es un servicio digital remoto para crear, procesar y preparar archivos creativos.", "El servicio trabaja con videos, portadas, subtítulos, CV PDF, diseños, textos, música y paquetes de publicación."], [("Solo digital", "Todos los resultados se entregan online dentro del espacio de trabajo."), ("Herramientas", "Convertidor, Shorts, portadas, subtítulos, CV, diseño, video, música y originalidad."), ("Para quién", "Creadores, estudios, freelancers y clientes que necesitan materiales digitales listos.")]),
        ("2. Flujo principal", ["Elige la herramienta adecuada, sube materiales y revisa la configuración antes de procesar.", "Cuando la tarea termine, abre la tarjeta, revisa la vista previa y descarga los resultados."], [("Elegir herramienta", "Empieza por el objetivo: convertir, editar, diseñar, revisar texto o preparar un paquete."), ("Preparar datos", "Usa nombres claros, buenas fuentes y una descripción precisa."), ("Revisar", "Comprueba preview, texto, tiempos, formato y calidad.")]),
        ("3. Pago, acceso y límites", ["El acceso de pago se activa automáticamente tras un pago online correcto.", "El plan puede incluir duración, almacenamiento, límites, herramientas y prioridad."], [("Activación", "El acceso suele aparecer justo después de confirmar el pago."), ("Límites", "Dependen del plan elegido y de las reglas del servicio."), ("Entrega", "No hay entrega física; los archivos se proporcionan digitalmente.")]),
        ("4. Preparación de archivos", ["Buenos materiales de origen mejoran el resultado y reducen repeticiones.", "Antes de subir, revisa formato, tamaño, idioma, proporción, audio y requisitos de plataforma."], [("Video", "Comprueba duración, orientación, resolución y requisitos de publicación."), ("Diseño", "Prepara título, colores de marca, referencias y medidas."), ("Documentos", "Usa DOCX, PDF o TXT si el formato está admitido.")]),
        ("5. Revisión del resultado", ["Antes de publicar, abre la vista previa o el archivo descargado y revísalo manualmente.", "Las herramientas con IA aceleran, pero la aprobación final corresponde al cliente."], [("Texto", "Revisa ortografía, nombres, enlaces, fechas, precios y contactos."), ("Medios", "Revisa nitidez, recorte, audio, subtítulos y exportación."), ("Repetir", "Si hacen falta cambios, repite la tarea o crea una nueva con mejores datos.")]),
        ("6. Soporte y problemas", ["Para soporte, envía email de cuenta, fecha de pago, plan, tarea, capturas y descripción.", "Si falla la subida o el procesamiento, revisa tamaño, formato, conexión y actualiza la página."], [("Pago", "Envía fecha, importe, email y confirmación."), ("Subida", "Prueba formato compatible, nombre corto y conexión estable."), ("Sin resultado", "Comprueba el estado; archivos complejos pueden tardar más.")]),
        ("7. Videos formativos y ejemplos", ["Aquí se publican lecciones cortas sobre los flujos principales.", "Ayudan a entender workspace, pago, descargas y preparación de publicación."], [("Inicio rápido", "Abrir workspace, elegir herramienta y lanzar la primera tarea."), ("Pago", "Entender activación, límites y descargas."), ("Publicación", "Cómo encajan portadas, subtítulos y ZIP.")]),
        ("8. Editor de video", ["El editor de video prepara clips, videos cortos y materiales para publicar.", "Útil para recorte, orden, preview, audio y exportación final."], [("Importar", "Sube el video y espera la vista previa."), ("Editar", "Trabaja escenas, orden, recorte y lógica visual."), ("Exportar", "Descarga el archivo final y revísalo antes de publicar.")]),
        ("9. Editor de música", ["El editor de música prepara audio para videos, previews y publicaciones.", "Usa solo audio sobre el que tengas derechos."], [("Subir audio", "Añade la pista y revisa que abra correctamente."), ("Preparar", "Comprueba volumen, duración, inicio, final y acentos."), ("Derechos", "Confirma derechos de uso antes de publicar.")]),
        ("10. Mesa de diseño y proyectos", ["La mesa de diseño sirve para portadas, previews, banners, layouts y assets visuales.", "Los proyectos mantienen cada tarea creativa ordenada."], [("Proyectos", "Crea un proyecto por portada, preview, banner o layout."), ("Elementos", "Texto e imágenes no deben ocultar zonas importantes."), ("Exportar", "Descarga PNG, JPG o WEBP y revisa legibilidad móvil.")]),
        ("11. Originalidad, documentos y textos", ["La comprobación analiza textos, documentos, borradores y artículos por originalidad, repeticiones y AI-risk.", "Es una guía analítica, no una conclusión legal, académica o editorial."], [("Texto", "Pega texto para revisar estructura, repeticiones y posibles señales de IA."), ("Documentos", "Sube DOCX, PDF o TXT admitidos dentro del límite."), ("Informe", "Úsalo como checklist para reescribir, añadir fuentes y comprobar hechos.")]),
        ("12. Paquete de publicación", ["El paquete reúne ZIP, preview, textos, portadas, subtítulos y archivos relacionados.", "Sirve para entregar materiales a un cliente, editor, diseñador o publicador."], [("Contenido", "Revisa qué archivos deben ir en el ZIP."), ("Nombres", "Usa nombres finales claros."), ("Revisión final", "Abre el archivo antes de enviar o publicar.")]),
    ],
})

DOCS_CONTENT["it"].update({
    "seo": "Documentazione CherryX Creator Studio: editor video, editor musicale, board design, controllo originalità, copertine, sottotitoli, CV PDF, pacchetti pubblicazione, pagamenti e download.",
    "sections": [
        ("1. Cos'è CherryX Creator Studio", ["CherryX Creator Studio è un servizio digitale remoto per creare, elaborare e preparare file creativi.", "Il servizio lavora con video, copertine, sottotitoli, CV PDF, layout, testi, musica e pacchetti di pubblicazione."], [("Solo digitale", "Tutti i risultati sono consegnati online nel workspace."), ("Strumenti", "Convertitore, Shorts, copertine, sottotitoli, CV, design, video, musica e originalità."), ("Per chi", "Creator, studi, freelance e clienti che necessitano materiali digitali pronti.")]),
        ("2. Flusso principale", ["Scegli lo strumento adatto, carica i materiali e controlla le impostazioni.", "Quando l'attività è completa, apri la scheda, controlla l'anteprima e scarica i risultati."], [("Scegliere", "Parti dall'obiettivo: convertire, montare, progettare, controllare testo o creare un pacchetto."), ("Preparare", "Usa nomi chiari, fonti buone e descrizione precisa."), ("Controllare", "Verifica anteprima, testo, tempi, formato e qualità.")]),
        ("3. Pagamento, accesso e limiti", ["L'accesso a pagamento si attiva automaticamente dopo il pagamento online riuscito.", "Il piano può includere durata, storage, limiti, strumenti e priorità."], [("Attivazione", "L'accesso appare normalmente subito dopo la conferma."), ("Limiti", "Dipendono dal piano scelto e dalle regole del servizio."), ("Consegna", "Nessuna consegna fisica; file forniti digitalmente.")]),
        ("4. Preparazione file", ["Buoni file sorgente migliorano il risultato e riducono ripetizioni.", "Prima del caricamento controlla formato, dimensione, lingua, proporzioni, audio e requisiti piattaforma."], [("Video", "Controlla durata, orientamento, risoluzione e requisiti."), ("Design", "Prepara titolo, colori brand, riferimenti e dimensioni."), ("Documenti", "Usa DOCX, PDF o TXT quando supportati.")]),
        ("5. Controllo risultato", ["Prima di pubblicare, apri sempre anteprima o file scaricato.", "Gli strumenti AI aiutano, ma l'approvazione finale resta al cliente."], [("Testo", "Controlla ortografia, nomi, link, date, prezzi e contatti."), ("Media", "Controlla nitidezza, ritaglio, audio, sottotitoli ed export."), ("Ripeti", "Per correzioni rilancia l'attività o creane una nuova.")]),
        ("6. Supporto e problemi", ["Per supporto invia email account, data pagamento, piano, attività, screenshot e descrizione.", "Se upload o elaborazione fallisce, controlla dimensione, formato, connessione e aggiorna."], [("Pagamento", "Invia data, importo, email e conferma."), ("Upload", "Prova formato supportato, nome breve e connessione stabile."), ("Nessun risultato", "Controlla lo stato; file complessi richiedono più tempo.")]),
        ("7. Video formativi ed esempi", ["Qui appaiono lezioni brevi sui flussi principali.", "Aiutano a capire workspace, pagamento, download e preparazione alla pubblicazione."], [("Avvio rapido", "Aprire workspace, scegliere strumento e avviare attività."), ("Pagamento", "Capire attivazione, limiti e download."), ("Pubblicazione", "Collegare copertine, sottotitoli e ZIP.")]),
        ("8. Editor video", ["L'editor video prepara clip, short e media pronti per la pubblicazione.", "Utile per ritaglio, ordine, anteprima, audio ed export finale."], [("Import", "Carica il video e attendi l'anteprima."), ("Montaggio", "Lavora su scene, ordine, ritaglio e logica visiva."), ("Export", "Scarica il file finale e controllalo prima di pubblicare.")]),
        ("9. Editor musicale", ["L'editor musicale prepara audio per video, preview e pubblicazioni.", "Usa solo audio di cui possiedi i diritti."], [("Audio", "Aggiungi la traccia e verifica che si apra."), ("Preparazione", "Controlla volume, durata, inizio, fine e accenti."), ("Diritti", "Conferma i diritti d'uso prima di pubblicare.")]),
        ("10. Board design e progetti", ["La board design serve per copertine, preview, banner, layout e asset visuali.", "I progetti mantengono separate e ordinate le attività creative."], [("Progetti", "Crea un progetto per ogni copertina, preview, banner o layout."), ("Elementi", "Testo e immagini non devono coprire aree importanti."), ("Export", "Scarica PNG, JPG o WEBP e verifica la leggibilità mobile.")]),
        ("11. Originalità, documenti e testi", ["Il controllo analizza testi, documenti, bozze e articoli per originalità, ripetizioni e AI-risk.", "Il risultato è una guida analitica, non un giudizio legale, accademico o editoriale."], [("Testo", "Incolla testo per controllare struttura, ripetizioni e segnali AI."), ("Documenti", "Carica DOCX, PDF o TXT supportati entro il limite."), ("Report", "Usalo come checklist per riscrivere, aggiungere fonti e verificare fatti.")]),
        ("12. Pacchetto pubblicazione", ["Il pacchetto raccoglie ZIP, anteprima, testi, copertine, sottotitoli e file collegati.", "Utile per consegnare materiali a cliente, montatore, designer o publisher."], [("Contenuto", "Verifica quali file devono entrare nello ZIP."), ("Nomi file", "Usa nomi finali chiari."), ("Controllo finale", "Apri l'archivio prima di inviare o pubblicare.")]),
    ],
})

DOCS_CONTENT["ka"].update({
    "seo": "CherryX Creator Studio დოკუმენტაცია: ვიდეო რედაქტორი, მუსიკის რედაქტორი, დიზაინ დაფა, უნიკალურობის შემოწმება, ქავერები, სუბტიტრები, PDF რეზიუმე, პუბლიკაციის პაკეტები, გადახდა და ჩამოტვირთვა.",
    "sections": [
        ("1. რა არის CherryX Creator Studio", ["CherryX Creator Studio არის დისტანციური ციფრული სერვისი კრეატიული ფაილების შესაქმნელად და მოსამზადებლად.", "სერვისი მუშაობს ვიდეოებთან, ქავერებთან, სუბტიტრებთან, PDF რეზიუმეებთან, დიზაინებთან, ტექსტებთან, მუსიკასთან და პუბლიკაციის პაკეტებთან."], [("ციფრული ფორმატი", "ყველა შედეგი ხელმისაწვდომია ონლაინ workspace-ში."), ("ინსტრუმენტები", "კონვერტერი, Shorts, ქავერები, სუბტიტრები, რეზიუმე, დიზაინი, ვიდეო, მუსიკა და უნიკალურობა."), ("ვისთვის", "creator-ებისთვის, სტუდიებისთვის, ფრილანსერებისთვის და კლიენტებისთვის.")]),
        ("2. ძირითადი სამუშაო პროცესი", ["აირჩიეთ ინსტრუმენტი, ატვირთეთ მასალები და შეამოწმეთ პარამეტრები.", "დასრულების შემდეგ გახსენით ამოცანის ბარათი, ნახეთ preview და ჩამოტვირთეთ შედეგები."], [("ინსტრუმენტის არჩევა", "დაიწყეთ მიზნიდან: კონვერტაცია, მონტაჟი, დიზაინი, ტექსტის შემოწმება ან პაკეტი."), ("მონაცემები", "გამოიყენეთ გასაგები სახელები, ხარისხიანი წყაროები და ზუსტი აღწერა."), ("შემოწმება", "შეამოწმეთ preview, ტექსტი, დროები, ფორმატი და ხარისხი.")]),
        ("3. გადახდა, წვდომა და ლიმიტები", ["ფასიანი წვდომა ავტომატურად აქტიურდება წარმატებული ონლაინ გადახდის შემდეგ.", "გეგმა შეიძლება მოიცავდეს ვადას, საცავს, ფაილის ლიმიტებს, ინსტრუმენტებს და პრიორიტეტს."], [("აქტივაცია", "წვდომა ჩვეულებრივ ჩნდება გადახდის დადასტურების შემდეგ."), ("ლიმიტები", "ლიმიტები დამოკიდებულია გეგმაზე და სერვისის წესებზე."), ("მიწოდება", "ფიზიკური მიწოდება არ გამოიყენება; ფაილები ციფრულია.")]),
        ("4. ფაილების მომზადება", ["კარგი საწყისი ფაილები აუმჯობესებს შედეგს.", "ატვირთვამდე შეამოწმეთ ფორმატი, ზომა, ენა, პროპორციები, ხმა და პლატფორმის მოთხოვნები."], [("ვიდეო", "შეამოწმეთ ხანგრძლივობა, ორიენტაცია, რეზოლუცია და მოთხოვნები."), ("დიზაინი", "მოამზადეთ სათაური, ბრენდის ფერები, რეფერენსები და ზომები."), ("დოკუმენტები", "გამოიყენეთ DOCX, PDF ან TXT, თუ მხარდაჭერილია.")]),
        ("5. შედეგის შემოწმება", ["პუბლიკაციამდე ყოველთვის გახსენით preview ან ჩამოტვირთული ფაილი.", "AI ინსტრუმენტები აჩქარებს მუშაობას, მაგრამ საბოლოო დადასტურება კლიენტის პასუხისმგებლობაა."], [("ტექსტი", "შეამოწმეთ მართლწერა, სახელები, ბმულები, თარიღები, ფასები და კონტაქტები."), ("მედია", "შეამოწმეთ სიმკვეთრე, crop, ხმა, სუბტიტრები და ექსპორტი."), ("გამეორება", "საჭიროებისას თავიდან გაუშვით ამოცანა ან შექმენით ახალი.")]),
        ("6. მხარდაჭერა და პრობლემები", ["მხარდაჭერისთვის მიუთითეთ email, გადახდის თარიღი, გეგმა, ამოცანა, screenshot-ები და აღწერა.", "თუ ატვირთვა ან დამუშავება ვერ ხერხდება, შეამოწმეთ ზომა, ფორმატი, კავშირი და განაახლეთ გვერდი."], [("გადახდა", "გააგზავნეთ თარიღი, თანხა, email და დადასტურება."), ("ატვირთვა", "სცადეთ მხარდაჭერილი ფორმატი, მოკლე სახელი და სტაბილური კავშირი."), ("შედეგი არ არის", "შეამოწმეთ სტატუსი; რთულ ფაილებს მეტი დრო სჭირდება.")]),
        ("7. სასწავლო ვიდეოები და მაგალითები", ["აქ ქვეყნდება მოკლე გაკვეთილები CherryX Creator Studio-ს ძირითადი სცენარებისთვის.", "გაკვეთილები ხსნის workspace-ს, გადახდას, ჩამოტვირთვას და პუბლიკაციის მომზადებას."], [("სწრაფი სტარტი", "გახსენით workspace, აირჩიეთ ინსტრუმენტი და გაუშვით პირველი ამოცანა."), ("გადახდა", "გაიგეთ აქტივაცია, ლიმიტები და ჩამოტვირთვები."), ("პუბლიკაცია", "ქავერები, სუბტიტრები და ZIP პაკეტები ერთ პროცესში.")]),
        ("8. ვიდეო რედაქტორი", ["ვიდეო რედაქტორი ამზადებს კლიპებს და პუბლიკაციისთვის მზა ვიდეოებს.", "გამოსადეგია crop-ისთვის, სცენების რიგისთვის, preview-სთვის, აუდიოსთვის და ექსპორტისთვის."], [("იმპორტი", "ატვირთეთ ვიდეო და დაელოდეთ preview-ს."), ("მონტაჟი", "იმუშავეთ სცენებზე, რიგზე, crop-ზე და ვიზუალურ ლოგიკაზე."), ("ექსპორტი", "ჩამოტვირთეთ ფინალური ფაილი და შეამოწმეთ.")]),
        ("9. მუსიკის რედაქტორი", ["მუსიკის რედაქტორი ამზადებს აუდიოს ვიდეოებისთვის და პუბლიკაციებისთვის.", "გამოიყენეთ მხოლოდ აუდიო, რომლის გამოყენების უფლებაც გაქვთ."], [("აუდიო", "დაამატეთ ბილიკი და შეამოწმეთ გახსნა."), ("მომზადება", "შეამოწმეთ ხმა, ხანგრძლივობა, დასაწყისი, დასასრული და აქცენტები."), ("უფლებები", "პუბლიკაციამდე დაადასტურეთ გამოყენების უფლება.")]),
        ("10. დიზაინ-დაფა და პროექტები", ["დიზაინ-დაფა არის workspace ქავერებისთვის, preview-ებისთვის, ბანერებისთვის და მაკეტებისთვის.", "პროექტები ინახავს კრეატიულ ამოცანებს ორგანიზებულად."], [("პროექტები", "შექმენით ცალკე პროექტი თითოეული ქავერისთვის ან მაკეტისთვის."), ("ელემენტები", "ტექსტმა და სურათებმა მნიშვნელოვანი ზონები არ უნდა დაფაროს."), ("ექსპორტი", "ჩამოტვირთეთ PNG, JPG ან WEBP და შეამოწმეთ მობილურზე.")]),
        ("11. უნიკალურობა, დოკუმენტები და ტექსტები", ["შემოწმება აანალიზებს ტექსტებს, დოკუმენტებს და სტატიებს უნიკალურობაზე, გამეორებებზე და AI-risk-ზე.", "შედეგი არის ანალიტიკური ორიენტირი და არა იურიდიული ან აკადემიური დასკვნა."], [("ტექსტი", "ჩასვით ტექსტი სტრუქტურისა და გამეორებების შესამოწმებლად."), ("დოკუმენტები", "ატვირთეთ მხარდაჭერილი DOCX, PDF ან TXT ლიმიტის ფარგლებში."), ("ანგარიში", "გამოიყენეთ როგორც checklist გადამუშავებისთვის და ფაქტების შემოწმებისთვის.")]),
        ("12. პუბლიკაციის პაკეტი", ["პაკეტი აგროვებს ZIP-ს, preview-ს, ტექსტებს, ქავერებს, სუბტიტრებს და დაკავშირებულ ფაილებს.", "მოსახერხებელია მასალების კლიენტისთვის, მონტაჟორისთვის ან დიზაინერისთვის გადასაცემად."], [("შემადგენლობა", "ZIP-ის ჩამოტვირთვამდე შეამოწმეთ ფაილების სია."), ("სახელები", "გამოიყენეთ გასაგები საბოლოო სახელები."), ("ფინალური შემოწმება", "გახსენით არქივი გაგზავნამდე ან პუბლიკაციამდე.")]),
    ],
})

DOCS_CONTENT["hy"].update({
    "seo": "CherryX Creator Studio փաստաթղթեր՝ վիդեո խմբագիր, երաժշտական խմբագիր, դիզայն տախտակ, ունիկալության ստուգում, cover-ներ, ենթագրեր, PDF ռեզյումե, հրապարակման փաթեթներ, վճարում և ներբեռնում։",
    "sections": [
        ("1. Ինչ է CherryX Creator Studio-ն", ["CherryX Creator Studio-ն հեռավար թվային ծառայություն է ստեղծագործական ֆայլեր ստեղծելու և պատրաստելու համար։", "Ծառայությունն աշխատում է վիդեոների, cover-ների, ենթագրերի, PDF ռեզյումեների, դիզայնների, տեքստերի, երաժշտության և հրապարակման փաթեթների հետ։"], [("Թվային ձևաչափ", "Բոլոր արդյունքները հասանելի են առցանց workspace-ում։"), ("Գործիքներ", "Կոնվերտեր, Shorts, cover-ներ, ենթագրեր, ռեզյումե, դիզայն, վիդեո, երաժշտություն և ունիկալություն։"), ("Ում համար", "Creator-ների, ստուդիաների, freelancer-ների և հաճախորդների համար։")]),
        ("2. Հիմնական աշխատանքային ընթացք", ["Ընտրեք գործիք, վերբեռնեք նյութերը և ստուգեք կարգավորումները։", "Ավարտից հետո բացեք առաջադրանքի քարտը, ստուգեք preview-ն և ներբեռնեք արդյունքները։"], [("Գործիք", "Սկսեք նպատակից՝ փոխարկել, մոնտաժել, դիզայն անել, ստուգել տեքստ կամ հավաքել փաթեթ։"), ("Տվյալներ", "Օգտագործեք պարզ ֆայլանուններ, որակյալ աղբյուրներ և ճշգրիտ նկարագրություն։"), ("Ստուգում", "Ստուգեք preview, տեքստ, ժամանակներ, ձևաչափ և որակ։")]),
        ("3. Վճարում, հասանելիություն և սահմանաչափեր", ["Վճարովի հասանելիությունը ակտիվանում է հաջող առցանց վճարումից հետո։", "Պլանը կարող է ներառել ժամկետ, պահեստ, ֆայլերի սահմանաչափեր, գործիքներ և առաջնահերթություն։"], [("Ակտիվացում", "Հասանելիությունը սովորաբար հայտնվում է վճարման հաստատումից հետո։"), ("Սահմանաչափեր", "Կախված են ընտրված պլանից և ծառայության կանոններից։"), ("Առաքում", "Ֆիզիկական առաքում չկա․ ֆայլերը թվային են։")]),
        ("4. Ֆայլերի պատրաստում", ["Լավ աղբյուրները բարելավում են արդյունքը։", "Վերբեռնելուց առաջ ստուգեք ձևաչափը, չափը, լեզուն, համամասնությունները, ձայնը և հարթակի պահանջները։"], [("Վիդեո", "Ստուգեք տևողությունը, ուղղությունը, լուծաչափը և պահանջները։"), ("Դիզայն", "Պատրաստեք վերնագիր, brand գույներ, reference-ներ և չափեր։"), ("Փաստաթղթեր", "Օգտագործեք DOCX, PDF կամ TXT, եթե աջակցվում է։")]),
        ("5. Արդյունքի ստուգում", ["Հրապարակելուց առաջ միշտ բացեք preview-ն կամ ներբեռնված ֆայլը։", "AI գործիքները արագացնում են, բայց վերջնական հաստատումը հաճախորդի պատասխանատվությունն է։"], [("Տեքստ", "Ստուգեք ուղղագրությունը, անունները, հղումները, ամսաթվերը, գները և կոնտակտները։"), ("Մեդիա", "Ստուգեք հստակությունը, crop-ը, ձայնը, ենթագրերը և export-ը։"), ("Կրկնել", "Փոփոխությունների համար կրկնեք առաջադրանքը կամ ստեղծեք նոր։")]),
        ("6. Աջակցություն և խնդիրներ", ["Աջակցության համար ուղարկեք email, վճարման ամսաթիվ, պլան, առաջադրանք, screenshot-ներ և նկարագրություն։", "Եթե վերբեռնումը կամ մշակումը չի աշխատում, ստուգեք չափը, ձևաչափը, կապը և թարմացրեք էջը։"], [("Վճարում", "Ուղարկեք ամսաթիվ, գումար, email և հաստատում։"), ("Վերբեռնում", "Փորձեք աջակցվող ձևաչափ, կարճ անուն և կայուն կապ։"), ("Արդյունք չկա", "Ստուգեք կարգավիճակը․ բարդ ֆայլերը կարող են երկար մշակվել։")]),
        ("7. Ուսուցողական տեսանյութեր և օրինակներ", ["Այստեղ հրապարակվում են կարճ դասեր CherryX Creator Studio-ի հիմնական սցենարների համար։", "Դասերը բացատրում են workspace-ը, վճարումը, ներբեռնումը և հրապարակման պատրաստումը։"], [("Արագ սկիզբ", "Բացեք workspace-ը, ընտրեք գործիք և գործարկեք առաջին առաջադրանքը։"), ("Վճարում", "Հասկացեք ակտիվացումը, սահմանաչափերը և ներբեռնումները։"), ("Հրապարակում", "Cover-ներ, ենթագրեր և ZIP փաթեթներ մեկ workflow-ում։")]),
        ("8. Վիդեո խմբագիր", ["Վիդեո խմբագիրը պատրաստում է հոլովակներ և հրապարակման պատրաստ վիդեոներ։", "Օգտակար է crop-ի, տեսարանների հերթականության, preview-ի, աուդիոյի և export-ի համար։"], [("Import", "Վերբեռնեք վիդեոն և սպասեք preview-ին։"), ("Մոնտաժ", "Աշխատեք տեսարանների, հերթականության, crop-ի և վիզուալ տրամաբանության հետ։"), ("Export", "Ներբեռնեք վերջնական ֆայլը և ստուգեք։")]),
        ("9. Երաժշտական խմբագիր", ["Երաժշտական խմբագիրը պատրաստում է աուդիո վիդեոների և հրապարակումների համար։", "Օգտագործեք միայն աուդիո, որի օգտագործման իրավունք ունեք։"], [("Աուդիո", "Ավելացրեք track-ը և ստուգեք բացումը։"), ("Պատրաստում", "Ստուգեք ձայնը, տևողությունը, սկիզբը, վերջը և շեշտերը։"), ("Իրավունքներ", "Հրապարակումից առաջ հաստատեք օգտագործման իրավունքը։")]),
        ("10. Դիզայն տախտակ և նախագծեր", ["Դիզայն տախտակը workspace է cover-ների, preview-ների, բաներների և layout-ների համար։", "Նախագծերը պահում են ստեղծագործական առաջադրանքները կազմակերպված։"], [("Նախագծեր", "Ստեղծեք առանձին նախագիծ յուրաքանչյուր cover-ի կամ layout-ի համար։"), ("Էլեմենտներ", "Տեքստն ու պատկերները չպետք է փակեն կարևոր գոտիները։"), ("Export", "Ներբեռնեք PNG, JPG կամ WEBP և ստուգեք հեռախոսով։")]),
        ("11. Ունիկալություն, փաստաթղթեր և տեքստեր", ["Ստուգումը վերլուծում է տեքստեր, փաստաթղթեր և հոդվածներ ունիկալության, կրկնությունների և AI-risk-ի համար։", "Արդյունքը վերլուծական ուղեցույց է, ոչ թե իրավական կամ ակադեմիական եզրակացություն։"], [("Տեքստ", "Տեղադրեք տեքստ՝ կառուցվածքն ու կրկնությունները ստուգելու համար։"), ("Փաստաթղթեր", "Վերբեռնեք աջակցվող DOCX, PDF կամ TXT սահմանաչափի մեջ։"), ("Զեկույց", "Օգտագործեք որպես checklist՝ վերաշարադրելու և փաստերը ստուգելու համար։")]),
        ("12. Հրապարակման փաթեթ", ["Փաթեթը հավաքում է ZIP, preview, տեքստեր, cover-ներ, ենթագրեր և կապված ֆայլեր։", "Հարմար է նյութերը հաճախորդին, մոնտաժողին կամ դիզայներին փոխանցելու համար։"], [("Կազմ", "ZIP-ը ներբեռնելուց առաջ ստուգեք ֆայլերի ցանկը։"), ("Անուններ", "Օգտագործեք պարզ վերջնական անուններ։"), ("Վերջնական ստուգում", "Բացեք արխիվը ուղարկելուց կամ հրապարակելուց առաջ։")]),
    ],
})


def documentation_content(language: str | None) -> dict[str, object]:
    language = clean_language(language)
    return DOCS_CONTENT.get(language) or DOCS_CONTENT["en"]
