from __future__ import annotations

from django.urls import path

from . import views


app_name = "studio"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("app/", views.index, name="index"),
    path("app/stats/<str:section>/", views.dashboard_detail, name="dashboard_detail"),
    path("app/video-projects/", views.video_project_list, name="video_project_list"),
    path("app/video-editor/", views.video_editor, name="video_editor"),
    path("app/design-projects/", views.design_project_list, name="design_project_list"),
    path("api/video-projects/", views.video_projects, name="video_projects"),
    path("api/video-projects/create/", views.create_video_project, name="create_video_project"),
    path("api/video-projects/delete/", views.delete_video_projects, name="delete_video_projects"),
    path("api/video-projects/<int:project_id>/", views.video_project_detail, name="video_project_detail"),
    path("api/video-projects/<int:project_id>/save/", views.save_video_project, name="save_video_project"),
    path("api/video-projects/<int:project_id>/rename/", views.rename_video_project, name="rename_video_project"),
    path("api/video-projects/<int:project_id>/exports/", views.list_video_project_exports, name="list_video_project_exports"),
    path("api/video-projects/<int:project_id>/export/", views.start_video_project_export, name="start_video_project_export"),
    path("api/video-projects/<int:project_id>/cover/", views.export_video_project_cover, name="export_video_project_cover"),
    path("api/video-projects/<int:project_id>/export/<str:job_id>/", views.video_project_export_status, name="video_project_export_status"),
    path("api/video-projects/<int:project_id>/export/<str:job_id>/cancel/", views.cancel_video_project_export, name="cancel_video_project_export"),
    path("api/video-projects/<int:project_id>/export/<str:job_id>/download/", views.download_video_project_export, name="download_video_project_export"),
    path("api/video-projects/<int:project_id>/delete/", views.delete_video_project, name="delete_video_project"),
    path("api/video-projects/<int:project_id>/assets/", views.upload_video_project_asset, name="upload_video_project_asset"),
    path("api/video-projects/<int:project_id>/assets/<int:asset_id>/preview/", views.preview_video_project_asset, name="video_project_asset_preview"),
    path("api/video-projects/<int:project_id>/assets/<int:asset_id>/waveform/", views.video_project_asset_waveform, name="video_project_asset_waveform"),
    path("api/video-projects/<int:project_id>/assets/<int:asset_id>/thumbnail/", views.thumbnail_video_project_asset, name="video_project_asset_thumbnail"),
    path("api/video-projects/<int:project_id>/assets/<int:asset_id>/rename/", views.rename_video_project_asset, name="rename_video_project_asset"),
    path("api/video-projects/<int:project_id>/assets/<int:asset_id>/delete/", views.delete_video_project_asset, name="delete_video_project_asset"),
    path("api/design-projects/", views.design_projects, name="design_projects"),
    path("api/design-projects/create/", views.create_design_project, name="create_design_project"),
    path("api/design-projects/delete/", views.delete_design_projects, name="delete_design_projects"),
    path("api/design-projects/<int:project_id>/", views.design_project_detail, name="design_project_detail"),
    path("api/design-projects/<int:project_id>/save/", views.save_design_project, name="save_design_project"),
    path("api/design-projects/<int:project_id>/rename/", views.rename_design_project, name="rename_design_project"),
    path("api/design-projects/<int:project_id>/duplicate/", views.duplicate_design_project, name="duplicate_design_project"),
    path("api/design-projects/<int:project_id>/delete/", views.delete_design_project, name="delete_design_project"),
    path("api/design-projects/<int:project_id>/preview/", views.preview_design_project, name="design_project_preview"),
    path("api/design-projects/<int:project_id>/assets/", views.upload_design_project_asset, name="upload_design_project_asset"),
    path("api/design-projects/<int:project_id>/assets/<int:asset_id>/preview/", views.preview_design_project_asset, name="design_project_asset_preview"),
    path("invite/<str:token>/", views.workspace_invite, name="workspace_invite"),
    path("api/shares/", views.workspace_shares, name="workspace_shares"),
    path("api/shares/<int:share_id>/role/", views.workspace_share_role, name="workspace_share_role"),
    path("api/shares/<int:share_id>/revoke/", views.revoke_workspace_share, name="revoke_workspace_share"),
    path("app/designer/", views.designer_mode, name="designer"),
    path("accounts/register/", views.register, name="register"),
    path("accounts/login/", views.login_view, name="login"),
    path("accounts/settings/", views.account_settings, name="account_settings"),
    path("accounts/avatar/", views.account_avatar, name="account_avatar"),
    path("accounts/logout/", views.logout_view, name="logout"),
    path("language/", views.set_interface_language, name="set_language"),
    path("jobs/<str:job_id>/", views.job_detail, name="job_detail"),
    path("api/convert/", views.start_convert, name="start_convert"),
    path("api/youtube/", views.start_youtube, name="start_youtube"),
    path("api/cover/", views.start_cover, name="start_cover"),
    path("api/subtitles/", views.start_subtitles, name="start_subtitles"),
    path("api/package/", views.start_package, name="start_package"),
    path("api/resume/", views.start_resume, name="start_resume"),
    path("api/jobs/<str:job_id>/", views.job_status, name="job_status"),
    path("api/jobs/<str:job_id>/repeat/", views.repeat_job, name="repeat_job"),
    path("api/jobs/<str:job_id>/delete/", views.delete_job, name="delete_job"),
    path("preview/<str:job_id>/<int:index>/", views.preview_output, name="preview_output"),
    path("download/<str:job_id>/<int:index>/", views.download_output, name="download_output"),
    path("download/<str:job_id>/all/", views.download_all_outputs, name="download_all_outputs"),
    path("health/", views.health, name="health"),
]
